name = "skillbox"
account_id = "5281943bd26d5bdcf4c3915606cd6bfb"
compatibility_date = "2026-07-03"
workers_dev = false

[assets]
directory = "./site"

[[routes]]
pattern = "skillbox.hasanshoaib.com"
custom_domain = true
